name: Test and Notify

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Generate Prisma client
        run: npx prisma generate
      
      - name: Push database schema
        run: npx prisma db push
      
      - name: Run tests
        run: npm test
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            coverage/
            junit.xml
          retention-days: 1

  notify:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup notification script
        run: |
          chmod +x scripts/notify-pr-author.sh
      
      - name: Send notification
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MON_SUPER_LIEN: ${{ secrets.MON_SUPER_LIEN }}
          TEST_JOB_RESULT: ${{ needs.test.result }}
        run: ./scripts/notify-pr-author.sh 